import { PrismaClient, Role } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  const saltRounds = 10;

  const users = [
    // ADMINs (2)
    {
      name: "Super",
      surname: "Admin",
      email: "admin@rotaly.com",
      phone: "+905551112200",
      role: Role.ADMIN,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Admin123!", saltRounds),
    },

    // OWNERS (8)
    // OWNERs (15)
    {
      name: "Ahmet",
      surname: "Yılmaz",
      email: "otel.sahibi1@rotaly.com",
      phone: "+905551113301",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ayşe",
      surname: "Kaya",
      email: "otel.sahibi2@rotaly.com",
      phone: "+905551113302",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ali",
      surname: "Demir",
      email: "otel.sahibi3@rotaly.com",
      phone: "+905551113303",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Fatma",
      surname: "Çelik",
      email: "otel.sahibi4@rotaly.com",
      phone: "+905551113304",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Mehmet",
      surname: "Şahin",
      email: "otel.sahibi5@rotaly.com",
      phone: "+905551113305",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Zeynep",
      surname: "Yıldız",
      email: "otel.sahibi6@rotaly.com",
      phone: "+905551113306",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Mustafa",
      surname: "Arslan",
      email: "otel.sahibi7@rotaly.com",
      phone: "+905551113307",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Esra",
      surname: "Aydın",
      email: "otel.sahibi8@rotaly.com",
      phone: "+905551113308",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Burak",
      surname: "Koç",
      email: "otel.sahibi9@rotaly.com",
      phone: "+905551113309",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Selin",
      surname: "Tekin",
      email: "otel.sahibi10@rotaly.com",
      phone: "+905551113310",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Kaan",
      surname: "Doğan",
      email: "otel.sahibi11@rotaly.com",
      phone: "+905551113311",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "İrem",
      surname: "Kurt",
      email: "otel.sahibi12@rotaly.com",
      phone: "+905551113312",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ozan",
      surname: "Çetin",
      email: "otel.sahibi13@rotaly.com",
      phone: "+905551113313",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Derin",
      surname: "Kılıç",
      email: "otel.sahibi14@rotaly.com",
      phone: "+905551113314",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Berkay",
      surname: "Şen",
      email: "otel.sahibi15@rotaly.com",
      phone: "+905551113315",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },

    {
      name: "Mehmet",
      surname: "Yılmaz",
      email: "mehmet.hotel@rotaly.com",
      phone: "+905551112210",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ayşe",
      surname: "Kaya",
      email: "ayse.hotel@rotaly.com",
      phone: "+905551112211",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ali",
      surname: "Demir",
      email: "ali.hotel@rotaly.com",
      phone: "+905551112212",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Fatma",
      surname: "Çelik",
      email: "fatma.hotel@rotaly.com",
      phone: "+905551112213",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Ahmet",
      surname: "Şahin",
      email: "ahmet.hotel@rotaly.com",
      phone: "+905551112214",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Zeynep",
      surname: "Yıldız",
      email: "zeynep.hotel@rotaly.com",
      phone: "+905551112215",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Mustafa",
      surname: "Arslan",
      email: "mustafa.hotel@rotaly.com",
      phone: "+905551112216",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },
    {
      name: "Esra",
      surname: "Aydın",
      email: "esra.hotel@rotaly.com",
      phone: "+905551112217",
      role: Role.OWNER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Owner123!", saltRounds),
    },

    // SUPPORT (5)
    {
      name: "Destek",
      surname: "Personeli1",
      email: "destek1@rotaly.com",
      phone: "+905551114401",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Destek",
      surname: "Personeli2",
      email: "destek2@rotaly.com",
      phone: "+905551114402",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Destek",
      surname: "Personeli3",
      email: "destek3@rotaly.com",
      phone: "+905551114403",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Destek",
      surname: "Personeli4",
      email: "destek4@rotaly.com",
      phone: "+905551114404",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Destek",
      surname: "Personeli5",
      email: "destek5@rotaly.com",
      phone: "+905551114405",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Support",
      surname: "Team1",
      email: "support1@rotaly.com",
      phone: "+905551112220",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Support",
      surname: "Team2",
      email: "support2@rotaly.com",
      phone: "+905551112221",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Support",
      surname: "Team3",
      email: "support3@rotaly.com",
      phone: "+905551112222",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Support",
      surname: "Team4",
      email: "support4@rotaly.com",
      phone: "+905551112223",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },
    {
      name: "Support",
      surname: "Team5",
      email: "support5@rotaly.com",
      phone: "+905551112224",
      role: Role.SUPPORT,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Support123!", saltRounds),
    },

    // CUSTOMERS (35)
    {
      name: "Emre",
      surname: "Yılmaz",
      email: "musteri1@example.com",
      phone: "+905551115501",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Selin",
      surname: "Kaya",
      email: "musteri2@example.com",
      phone: "+905551115502",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Burak",
      surname: "Demir",
      email: "musteri3@example.com",
      phone: "+905551115503",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Deniz",
      surname: "Çelik",
      email: "musteri4@example.com",
      phone: "+905551115504",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Elif",
      surname: "Şahin",
      email: "musteri5@example.com",
      phone: "+905551115505",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Can",
      surname: "Öztürk",
      email: "musteri6@example.com",
      phone: "+905551115506",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Aylin",
      surname: "Arslan",
      email: "musteri7@example.com",
      phone: "+905551115507",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Mert",
      surname: "Aydın",
      email: "musteri8@example.com",
      phone: "+905551115508",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "İrem",
      surname: "Yıldız",
      email: "musteri9@example.com",
      phone: "+905551115509",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Cem",
      surname: "Korkmaz",
      email: "musteri10@example.com",
      phone: "+905551115510",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Berk",
      surname: "Aksoy",
      email: "musteri11@example.com",
      phone: "+905551115511",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ceren",
      surname: "Güneş",
      email: "musteri12@example.com",
      phone: "+905551115512",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Kaan",
      surname: "Erdoğan",
      email: "musteri13@example.com",
      phone: "+905551115513",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Zehra",
      surname: "Koç",
      email: "musteri14@example.com",
      phone: "+905551115514",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Onur",
      surname: "Özdemir",
      email: "musteri15@example.com",
      phone: "+905551115515",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Merve",
      surname: "Tekin",
      email: "musteri16@example.com",
      phone: "+905551115516",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Tolga",
      surname: "Doğan",
      email: "musteri17@example.com",
      phone: "+905551115517",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Sude",
      surname: "Kurt",
      email: "musteri18@example.com",
      phone: "+905551115518",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ege",
      surname: "Çetin",
      email: "musteri19@example.com",
      phone: "+905551115519",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Yağmur",
      surname: "Kılıç",
      email: "musteri20@example.com",
      phone: "+905551115520",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Alper",
      surname: "Şen",
      email: "musteri21@example.com",
      phone: "+905551115521",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Damla",
      surname: "Yalçın",
      email: "musteri22@example.com",
      phone: "+905551115522",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Serkan",
      surname: "Aslan",
      email: "musteri23@example.com",
      phone: "+905551115523",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Melis",
      surname: "Özer",
      email: "musteri24@example.com",
      phone: "+905551115524",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Umut",
      surname: "Demirci",
      email: "musteri25@example.com",
      phone: "+905551115525",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Beyza",
      surname: "Çakır",
      email: "musteri26@example.com",
      phone: "+905551115526",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Kerem",
      surname: "Acar",
      email: "musteri27@example.com",
      phone: "+905551115527",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "İpek",
      surname: "Tuncer",
      email: "musteri28@example.com",
      phone: "+905551115528",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Barış",
      surname: "Güler",
      email: "musteri29@example.com",
      phone: "+905551115529",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Eylül",
      surname: "Aktaş",
      email: "musteri30@example.com",
      phone: "+905551115530",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Yiğit",
      surname: "Bulut",
      email: "musteri31@example.com",
      phone: "+905551115531",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Defne",
      surname: "Altın",
      email: "musteri32@example.com",
      phone: "+905551115532",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ozan",
      surname: "Keskin",
      email: "musteri33@example.com",
      phone: "+905551115533",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Derin",
      surname: "Sarı",
      email: "musteri34@example.com",
      phone: "+905551115534",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Berkay",
      surname: "Avcı",
      email: "musteri35@example.com",
      phone: "+905551115535",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Aslı",
      surname: "Güneş",
      email: "musteri36@example.com",
      phone: "+905551115536",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Cenk",
      surname: "Yıldırım",
      email: "musteri37@example.com",
      phone: "+905551115537",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Gizem",
      surname: "Ateş",
      email: "musteri38@example.com",
      phone: "+905551115538",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Hakan",
      surname: "Deniz",
      email: "musteri39@example.com",
      phone: "+905551115539",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Selen",
      surname: "Toprak",
      email: "musteri40@example.com",
      phone: "+905551115540",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Murat",
      surname: "Dağ",
      email: "musteri41@example.com",
      phone: "+905551115541",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Pınar",
      surname: "ırmak",
      email: "musteri42@example.com",
      phone: "+905551115542",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Osman",
      surname: "Göl",
      email: "musteri43@example.com",
      phone: "+905551115543",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Tuğçe",
      surname: "Yıldız",
      email: "musteri44@example.com",
      phone: "+905551115544",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Fatih",
      surname: "Ağaç",
      email: "musteri45@example.com",
      phone: "+905551115545",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Burcu",
      surname: "Taş",
      email: "musteri46@example.com",
      phone: "+905551115546",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Emre",
      surname: "Bulut",
      email: "musteri47@example.com",
      phone: "+905551115547",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Sevim",
      surname: "Yüce",
      email: "musteri48@example.com",
      phone: "+905551115548",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Gökhan",
      surname: "Savaş",
      email: "musteri49@example.com",
      phone: "+905551115549",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Nihal",
      surname: "Barış",
      email: "musteri50@example.com",
      phone: "+905551115550",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Cemil",
      surname: "Uysal",
      email: "musteri51@example.com",
      phone: "+905551115551",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Esma",
      surname: "Doğru",
      email: "musteri52@example.com",
      phone: "+905551115552",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Salih",
      surname: "Eğri",
      email: "musteri53@example.com",
      phone: "+905551115553",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Hande",
      surname: "Açık",
      email: "musteri54@example.com",
      phone: "+905551115554",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Bora",
      surname: "Kapalı",
      email: "musteri55@example.com",
      phone: "+905551115555",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Gül",
      surname: "Siyah",
      email: "musteri56@example.com",
      phone: "+905551115556",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Canan",
      surname: "Beyaz",
      email: "musteri57@example.com",
      phone: "+905551115557",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Metin",
      surname: "Uzun",
      email: "musteri58@example.com",
      phone: "+905551115558",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Sezen",
      surname: "Kısa",
      email: "musteri59@example.com",
      phone: "+905551115559",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Hülya",
      surname: "Büyük",
      email: "musteri60@example.com",
      phone: "+905551115560",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ceyda",
      surname: "Küçük",
      email: "musteri61@example.com",
      phone: "+905551115561",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Erkan",
      surname: "Yeni",
      email: "musteri62@example.com",
      phone: "+905551115562",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Burcu",
      surname: "Eski",
      email: "musteri63@example.com",
      phone: "+905551115563",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Levent",
      surname: "Güçlü",
      email: "musteri64@example.com",
      phone: "+905551115564",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Nalan",
      surname: "Zayıf",
      email: "musteri65@example.com",
      phone: "+905551115565",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Serap",
      surname: "Mutlu",
      email: "musteri66@example.com",
      phone: "+905551115566",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Yavuz",
      surname: "Hüzünlü",
      email: "musteri67@example.com",
      phone: "+905551115567",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Dilek",
      surname: "Zengin",
      email: "musteri68@example.com",
      phone: "+905551115568",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Fikret",
      surname: "Fakir",
      email: "musteri69@example.com",
      phone: "+905551115569",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Emre",
      surname: "Yılmaz",
      email: "customer1@example.com",
      phone: "+905551112300",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Selin",
      surname: "Kaya",
      email: "customer2@example.com",
      phone: "+905551112301",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Burak",
      surname: "Demir",
      email: "customer3@example.com",
      phone: "+905551112302",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Deniz",
      surname: "Çelik",
      email: "customer4@example.com",
      phone: "+905551112303",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Elif",
      surname: "Şahin",
      email: "customer5@example.com",
      phone: "+905551112304",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Can",
      surname: "Öztürk",
      email: "customer6@example.com",
      phone: "+905551112305",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Aylin",
      surname: "Arslan",
      email: "customer7@example.com",
      phone: "+905551112306",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Mert",
      surname: "Aydın",
      email: "customer8@example.com",
      phone: "+905551112307",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "İrem",
      surname: "Yıldız",
      email: "customer9@example.com",
      phone: "+905551112308",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Cem",
      surname: "Korkmaz",
      email: "customer10@example.com",
      phone: "+905551112309",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Berk",
      surname: "Aksoy",
      email: "customer11@example.com",
      phone: "+905551112310",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ceren",
      surname: "Güneş",
      email: "customer12@example.com",
      phone: "+905551112311",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Kaan",
      surname: "Erdoğan",
      email: "customer13@example.com",
      phone: "+905551112312",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Zehra",
      surname: "Koç",
      email: "customer14@example.com",
      phone: "+905551112313",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Onur",
      surname: "Özdemir",
      email: "customer15@example.com",
      phone: "+905551112314",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Merve",
      surname: "Tekin",
      email: "customer16@example.com",
      phone: "+905551112315",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Tolga",
      surname: "Doğan",
      email: "customer17@example.com",
      phone: "+905551112316",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Sude",
      surname: "Kurt",
      email: "customer18@example.com",
      phone: "+905551112317",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ege",
      surname: "Çetin",
      email: "customer19@example.com",
      phone: "+905551112318",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Yağmur",
      surname: "Kılıç",
      email: "customer20@example.com",
      phone: "+905551112319",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Alper",
      surname: "Şen",
      email: "customer21@example.com",
      phone: "+905551112320",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Damla",
      surname: "Yalçın",
      email: "customer22@example.com",
      phone: "+905551112321",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Serkan",
      surname: "Aslan",
      email: "customer23@example.com",
      phone: "+905551112322",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Melis",
      surname: "Özer",
      email: "customer24@example.com",
      phone: "+905551112323",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Umut",
      surname: "Demirci",
      email: "customer25@example.com",
      phone: "+905551112324",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Beyza",
      surname: "Çakır",
      email: "customer26@example.com",
      phone: "+905551112325",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Kerem",
      surname: "Acar",
      email: "customer27@example.com",
      phone: "+905551112326",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "İpek",
      surname: "Tuncer",
      email: "customer28@example.com",
      phone: "+905551112327",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Barış",
      surname: "Güler",
      email: "customer29@example.com",
      phone: "+905551112328",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Eylül",
      surname: "Aktaş",
      email: "customer30@example.com",
      phone: "+905551112329",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Yiğit",
      surname: "Bulut",
      email: "customer31@example.com",
      phone: "+905551112330",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Defne",
      surname: "Altın",
      email: "customer32@example.com",
      phone: "+905551112331",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Ozan",
      surname: "Keskin",
      email: "customer33@example.com",
      phone: "+905551112332",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Derin",
      surname: "Sarı",
      email: "customer34@example.com",
      phone: "+905551112333",
      role: Role.CUSTOMER,
      isVerified: true,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
    },
    {
      name: "Berkay",
      surname: "Avcı",
      email: "customer35@example.com",
      phone: "+905551112334",
      role: Role.CUSTOMER,
      isVerified: false,
      hashedPassword: await bcrypt.hash("Customer123!", saltRounds),
      verificationOTP: "123456",
      verificationOTPExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
  ];
  console.log(`Seed işlemi tamamlandı. ${users.length} kullanıcı eklendi.`);
}

main()
  .catch((e) => {
    console.error("Seed işlemi sırasında hata oluştu:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
