import {
  HotelType,
  PrismaClient,
  Role,
  RoomType,
  RoomFeature,
  HotelFeatures,
} from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  console.log("Seed işlemi başlatılıyor...");

  // 1. Admin kullanıcısı
  console.log("Admin kullanıcısı oluşturuluyor...");
  const hashedAdminPassword = await bcrypt.hash("Admin123!", 12);
  const admin = await prisma.user.upsert({
    where: { email: "admin@rotaly.com" },
    update: {},
    create: {
      name: "Super",
      surname: "Admin",
      email: "admin@rotaly.com",
      phone: "+905551112200",
      hashedPassword: hashedAdminPassword,
      role: Role.ADMIN,
      isVerified: true,
    },
  });
  console.log(`Admin kullanıcısı oluşturuldu: ${admin.email}`);

  // 2. Owner kullanıcıları (5 adet)
  console.log("Owner kullanıcıları oluşturuluyor...");
  const hashedOwnerPassword = await bcrypt.hash("Owner123!", 12);
  const owners = [
    {
      name: "Ahmet",
      surname: "Yılmaz",
      email: "owner1@rotaly.com",
      phone: "+905551113301",
    },
    {
      name: "Ayşe",
      surname: "Kaya",
      email: "owner2@rotaly.com",
      phone: "+905551113302",
    },
    {
      name: "Ali",
      surname: "Demir",
      email: "owner3@rotaly.com",
      phone: "+905551113303",
    },
    {
      name: "Fatma",
      surname: "Çelik",
      email: "owner4@rotaly.com",
      phone: "+905551113304",
    },
    {
      name: "Mehmet",
      surname: "Şahin",
      email: "owner5@rotaly.com",
      phone: "+905551113305",
    },

    {
      name: "Owner6",
      surname: "Soyad6",
      email: "owner6@rotaly.com",
      phone: "+905551113306",
    },
    {
      name: "Owner7",
      surname: "Soyad7",
      email: "owner7@rotaly.com",
      phone: "+905551113307",
    },
    {
      name: "Owner8",
      surname: "Soyad8",
      email: "owner8@rotaly.com",
      phone: "+905551113308",
    },
    {
      name: "Owner9",
      surname: "Soyad9",
      email: "owner9@rotaly.com",
      phone: "+905551113309",
    },
    {
      name: "Owner10",
      surname: "Soyad10",
      email: "owner10@rotaly.com",
      phone: "+905551113310",
    },
    {
      name: "Owner11",
      surname: "Soyad11",
      email: "owner11@rotaly.com",
      phone: "+905551113311",
    },
    {
      name: "Owner12",
      surname: "Soyad12",
      email: "owner12@rotaly.com",
      phone: "+905551113312",
    },
    {
      name: "Owner13",
      surname: "Soyad13",
      email: "owner13@rotaly.com",
      phone: "+905551113313",
    },
    {
      name: "Owner14",
      surname: "Soyad14",
      email: "owner14@rotaly.com",
      phone: "+905551113314",
    },
    {
      name: "Owner15",
      surname: "Soyad15",
      email: "owner15@rotaly.com",
      phone: "+905551113315",
    },
    {
      name: "Owner16",
      surname: "Soyad16",
      email: "owner16@rotaly.com",
      phone: "+905551113316",
    },
    {
      name: "Owner17",
      surname: "Soyad17",
      email: "owner17@rotaly.com",
      phone: "+905551113317",
    },
    {
      name: "Owner18",
      surname: "Soyad18",
      email: "owner18@rotaly.com",
      phone: "+905551113318",
    },
    {
      name: "Owner19",
      surname: "Soyad19",
      email: "owner19@rotaly.com",
      phone: "+905551113319",
    },
    {
      name: "Owner20",
      surname: "Soyad20",
      email: "owner20@rotaly.com",
      phone: "+905551113320",
    },
    {
      name: "Owner21",
      surname: "Soyad21",
      email: "owner21@rotaly.com",
      phone: "+905551113321",
    },
    {
      name: "Owner22",
      surname: "Soyad22",
      email: "owner22@rotaly.com",
      phone: "+905551113322",
    },
    {
      name: "Owner23",
      surname: "Soyad23",
      email: "owner23@rotaly.com",
      phone: "+905551113323",
    },
    {
      name: "Owner24",
      surname: "Soyad24",
      email: "owner24@rotaly.com",
      phone: "+905551113324",
    },
    {
      name: "Owner25",
      surname: "Soyad25",
      email: "owner25@rotaly.com",
      phone: "+905551113325",
    },
    {
      name: "Owner26",
      surname: "Soyad26",
      email: "owner26@rotaly.com",
      phone: "+905551113326",
    },
    {
      name: "Owner27",
      surname: "Soyad27",
      email: "owner27@rotaly.com",
      phone: "+905551113327",
    },
    {
      name: "Owner28",
      surname: "Soyad28",
      email: "owner28@rotaly.com",
      phone: "+905551113328",
    },
    {
      name: "Owner29",
      surname: "Soyad29",
      email: "owner29@rotaly.com",
      phone: "+905551113329",
    },
    {
      name: "Owner30",
      surname: "Soyad30",
      email: "owner30@rotaly.com",
      phone: "+905551113330",
    },
    {
      name: "Owner31",
      surname: "Soyad31",
      email: "owner31@rotaly.com",
      phone: "+905551113331",
    },
    {
      name: "Owner32",
      surname: "Soyad32",
      email: "owner32@rotaly.com",
      phone: "+905551113332",
    },
    {
      name: "Owner33",
      surname: "Soyad33",
      email: "owner33@rotaly.com",
      phone: "+905551113333",
    },
    {
      name: "Owner34",
      surname: "Soyad34",
      email: "owner34@rotaly.com",
      phone: "+905551113334",
    },
  ];

  const createdOwners = [];
  for (const ownerData of owners) {
    const owner = await prisma.user.upsert({
      where: { email: ownerData.email },
      update: {},
      create: {
        ...ownerData,
        hashedPassword: hashedOwnerPassword,
        role: Role.OWNER,
        isVerified: true,
      },
    });
    createdOwners.push(owner);
    console.log(`Owner kullanıcısı oluşturuldu: ${owner.email}`);
  }
  console.log(`${owners.length} adet owner kullanıcısı oluşturuldu.`);

  // 3. Support kullanıcıları (5 adet)
  console.log("Support kullanıcıları oluşturuluyor...");
  const hashedSupportPassword = await bcrypt.hash("Support123!", 12);
  const supportUsers = [
    {
      name: "Destek",
      surname: "Personeli1",
      email: "support1@rotaly.com",
      phone: "+905551114401",
    },
    {
      name: "Destek",
      surname: "Personeli2",
      email: "support2@rotaly.com",
      phone: "+905551114402",
    },
    {
      name: "Destek",
      surname: "Personeli3",
      email: "support3@rotaly.com",
      phone: "+905551114403",
    },
    {
      name: "Destek",
      surname: "Personeli4",
      email: "support4@rotaly.com",
      phone: "+905551114404",
    },
    {
      name: "Destek",
      surname: "Personeli5",
      email: "support5@rotaly.com",
      phone: "+905551114405",
    },
    {
      name: "Destek",
      surname: "Personeli6",
      email: "support6@rotaly.com",
      phone: "+905551114406",
    },
    {
      name: "Destek",
      surname: "Personeli7",
      email: "support7@rotaly.com",
      phone: "+905551114407",
    },
    {
      name: "Destek",
      surname: "Personeli8",
      email: "support8@rotaly.com",
      phone: "+905551114408",
    },
    {
      name: "Destek",
      surname: "Personeli9",
      email: "support9@rotaly.com",
      phone: "+905551114409",
    },
    {
      name: "Destek",
      surname: "Personeli10",
      email: "support10@rotaly.com",
      phone: "+905551114410",
    },
    {
      name: "Destek",
      surname: "Personeli11",
      email: "support11@rotaly.com",
      phone: "+905551114411",
    },
    {
      name: "Destek",
      surname: "Personeli12",
      email: "support12@rotaly.com",
      phone: "+905551114412",
    },
    {
      name: "Destek",
      surname: "Personeli13",
      email: "support13@rotaly.com",
      phone: "+905551114413",
    },
    {
      name: "Destek",
      surname: "Personeli14",
      email: "support14@rotaly.com",
      phone: "+905551114414",
    },
    {
      name: "Destek",
      surname: "Personeli15",
      email: "support15@rotaly.com",
      phone: "+905551114415",
    },
    {
      name: "Destek",
      surname: "Personeli16",
      email: "support16@rotaly.com",
      phone: "+905551114416",
    },
    {
      name: "Destek",
      surname: "Personeli17",
      email: "support17@rotaly.com",
      phone: "+905551114417",
    },
    {
      name: "Destek",
      surname: "Personeli18",
      email: "support18@rotaly.com",
      phone: "+905551114418",
    },
    {
      name: "Destek",
      surname: "Personeli19",
      email: "support19@rotaly.com",
      phone: "+905551114419",
    },
    {
      name: "Destek",
      surname: "Personeli20",
      email: "support20@rotaly.com",
      phone: "+905551114420",
    },
    {
      name: "Destek",
      surname: "Personeli21",
      email: "support21@rotaly.com",
      phone: "+905551114421",
    },
    {
      name: "Destek",
      surname: "Personeli22",
      email: "support22@rotaly.com",
      phone: "+905551114422",
    },
    {
      name: "Destek",
      surname: "Personeli23",
      email: "support23@rotaly.com",
      phone: "+905551114423",
    },
    {
      name: "Destek",
      surname: "Personeli24",
      email: "support24@rotaly.com",
      phone: "+905551114424",
    },
    {
      name: "Destek",
      surname: "Personeli25",
      email: "support25@rotaly.com",
      phone: "+905551114425",
    },
    {
      name: "Destek",
      surname: "Personeli26",
      email: "support26@rotaly.com",
      phone: "+905551114426",
    },
    {
      name: "Destek",
      surname: "Personeli27",
      email: "support27@rotaly.com",
      phone: "+905551114427",
    },
    {
      name: "Destek",
      surname: "Personeli28",
      email: "support28@rotaly.com",
      phone: "+905551114428",
    },
    {
      name: "Destek",
      surname: "Personeli29",
      email: "support29@rotaly.com",
      phone: "+905551114429",
    },
    {
      name: "Destek",
      surname: "Personeli30",
      email: "support30@rotaly.com",
      phone: "+905551114430",
    },
    {
      name: "Destek",
      surname: "Personeli31",
      email: "support31@rotaly.com",
      phone: "+905551114431",
    },
    {
      name: "Destek",
      surname: "Personeli32",
      email: "support32@rotaly.com",
      phone: "+905551114432",
    },
    {
      name: "Destek",
      surname: "Personeli33",
      email: "support33@rotaly.com",
      phone: "+905551114433",
    },
    {
      name: "Destek",
      surname: "Personeli34",
      email: "support34@rotaly.com",
      phone: "+905551114434",
    },
    {
      name: "Destek",
      surname: "Personeli35",
      email: "support35@rotaly.com",
      phone: "+905551114435",
    },
  ];

  for (const supportData of supportUsers) {
    const support = await prisma.user.upsert({
      where: { email: supportData.email },
      update: {},
      create: {
        ...supportData,
        hashedPassword: hashedSupportPassword,
        role: Role.SUPPORT,
        isVerified: true,
      },
    });
    console.log(`Support kullanıcısı oluşturuldu: ${support.email}`);
  }
  console.log(`${supportUsers.length} adet support kullanıcısı oluşturuldu.`);

  // 4. Normal kullanıcılar (70 adet)
  console.log("Normal kullanıcılar oluşturuluyor...");
  const hashedCustomerPassword = await bcrypt.hash("Customer123!", 12);
  const customers = [
    {
      name: "Emre",
      surname: "Yılmaz",
      email: "customer1@example.com",
      phone: "+905551115501",
    },
    {
      name: "Selin",
      surname: "Kaya",
      email: "customer2@example.com",
      phone: "+905551115502",
    },
    {
      name: "Burak",
      surname: "Demir",
      email: "customer3@example.com",
      phone: "+905551115503",
    },
    {
      name: "Deniz",
      surname: "Çelik",
      email: "customer4@example.com",
      phone: "+905551115504",
    },
    {
      name: "Elif",
      surname: "Şahin",
      email: "customer5@example.com",
      phone: "+905551115505",
    },
    {
      name: "Can",
      surname: "Öztürk",
      email: "customer6@example.com",
      phone: "+905551115506",
    },
    {
      name: "Aylin",
      surname: "Arslan",
      email: "customer7@example.com",
      phone: "+905551115507",
    },
    {
      name: "Mert",
      surname: "Aydın",
      email: "customer8@example.com",
      phone: "+905551115508",
    },
    {
      name: "İrem",
      surname: "Yıldız",
      email: "customer9@example.com",
      phone: "+905551115509",
    },
    {
      name: "Cem",
      surname: "Korkmaz",
      email: "customer10@example.com",
      phone: "+905551115510",
    },
    {
      name: "Berk",
      surname: "Aksoy",
      email: "customer11@example.com",
      phone: "+905551115511",
    },
    {
      name: "Ceren",
      surname: "Güneş",
      email: "customer12@example.com",
      phone: "+905551115512",
    },
    {
      name: "Kaan",
      surname: "Erdoğan",
      email: "customer13@example.com",
      phone: "+905551115513",
    },
    {
      name: "Zehra",
      surname: "Koç",
      email: "customer14@example.com",
      phone: "+905551115514",
    },
    {
      name: "Onur",
      surname: "Özdemir",
      email: "customer15@example.com",
      phone: "+905551115515",
    },
    {
      name: "Merve",
      surname: "Tekin",
      email: "customer16@example.com",
      phone: "+905551115516",
    },
    {
      name: "Tolga",
      surname: "Doğan",
      email: "customer17@example.com",
      phone: "+905551115517",
    },
    {
      name: "Sude",
      surname: "Kurt",
      email: "customer18@example.com",
      phone: "+905551115518",
    },
    {
      name: "Ege",
      surname: "Çetin",
      email: "customer19@example.com",
      phone: "+905551115519",
    },
    {
      name: "Yağmur",
      surname: "Kılıç",
      email: "customer20@example.com",
      phone: "+905551115520",
    },
    {
      name: "Ayşe",
      surname: "Yıldırım",
      email: "customer21@example.com",
      phone: "+905551115521",
    },
    {
      name: "Mustafa",
      surname: "Acar",
      email: "customer22@example.com",
      phone: "+905551115522",
    },
    {
      name: "Gizem",
      surname: "Ersoy",
      email: "customer23@example.com",
      phone: "+905551115523",
    },
    {
      name: "Umut",
      surname: "Can",
      email: "customer24@example.com",
      phone: "+905551115524",
    },
    {
      name: "Pınar",
      surname: "Yalçın",
      email: "customer25@example.com",
      phone: "+905551115525",
    },
    {
      name: "Serkan",
      surname: "Kara",
      email: "customer26@example.com",
      phone: "+905551115526",
    },
    {
      name: "Buse",
      surname: "Sarı",
      email: "customer27@example.com",
      phone: "+905551115527",
    },
    {
      name: "Okan",
      surname: "Aslan",
      email: "customer28@example.com",
      phone: "+905551115528",
    },
    {
      name: "Tuğçe",
      surname: "Demirci",
      email: "customer29@example.com",
      phone: "+905551115529",
    },
    {
      name: "Fatih",
      surname: "Koçak",
      email: "customer30@example.com",
      phone: "+905551115530",
    },
    {
      name: "Esra",
      surname: "Yücel",
      email: "customer31@example.com",
      phone: "+905551115531",
    },
    {
      name: "Emre",
      surname: "Güler",
      email: "customer32@example.com",
      phone: "+905551115532",
    },
    {
      name: "Seda",
      surname: "Ateş",
      email: "customer33@example.com",
      phone: "+905551115533",
    },
    {
      name: "Volkan",
      surname: "Erol",
      email: "customer34@example.com",
      phone: "+905551115534",
    },
    {
      name: "Hande",
      surname: "Bilgin",
      email: "customer35@example.com",
      phone: "+905551115535",
    },
    {
      name: "Gökhan",
      surname: "Aydın",
      email: "customer36@example.com",
      phone: "+905551115536",
    },
    {
      name: "Selen",
      surname: "Doğan",
      email: "customer37@example.com",
      phone: "+905551115537",
    },
    {
      name: "Burcu",
      surname: "Aksu",
      email: "customer38@example.com",
      phone: "+905551115538",
    },
    {
      name: "Alper",
      surname: "Yaman",
      email: "customer39@example.com",
      phone: "+905551115539",
    },
    {
      name: "Simge",
      surname: "Deniz",
      email: "customer40@example.com",
      phone: "+905551115540",
    },
    {
      name: "Oğuz",
      surname: "Özer",
      email: "customer41@example.com",
      phone: "+905551115541",
    },
    {
      name: "Pelin",
      surname: "Kurt",
      email: "customer42@example.com",
      phone: "+905551115542",
    },
    {
      name: "Cenk",
      surname: "Çakır",
      email: "customer43@example.com",
      phone: "+905551115543",
    },
    {
      name: "Ece",
      surname: "Taş",
      email: "customer44@example.com",
      phone: "+905551115544",
    },
    {
      name: "Murat",
      surname: "Yıldız",
      email: "customer45@example.com",
      phone: "+905551115545",
    },
    {
      name: "Aslı",
      surname: "Erkan",
      email: "customer46@example.com",
      phone: "+905551115546",
    },
    {
      name: "Hakan",
      surname: "Güneş",
      email: "customer47@example.com",
      phone: "+905551115547",
    },
    {
      name: "Zeynep",
      surname: "Kaya",
      email: "customer48@example.com",
      phone: "+905551115548",
    },
    {
      name: "Serdar",
      surname: "Arslan",
      email: "customer49@example.com",
      phone: "+905551115549",
    },
    {
      name: "Elif",
      surname: "Çetin",
      email: "customer50@example.com",
      phone: "+905551115550",
    },
    {
      name: "Barış",
      surname: "Demir",
      email: "customer51@example.com",
      phone: "+905551115551",
    },
    {
      name: "Tuğba",
      surname: "Aydın",
      email: "customer52@example.com",
      phone: "+905551115552",
    },
    {
      name: "Onur",
      surname: "Yılmaz",
      email: "customer53@example.com",
      phone: "+905551115553",
    },
    {
      name: "Duygu",
      surname: "Kara",
      email: "customer54@example.com",
      phone: "+905551115554",
    },
    {
      name: "İbrahim",
      surname: "Şahin",
      email: "customer55@example.com",
      phone: "+905551115555",
    },
    {
      name: "Merve",
      surname: "Öztürk",
      email: "customer56@example.com",
      phone: "+905551115556",
    },
    {
      name: "Caner",
      surname: "Tekin",
      email: "customer57@example.com",
      phone: "+905551115557",
    },
    {
      name: "Gülcan",
      surname: "Koç",
      email: "customer58@example.com",
      phone: "+905551115558",
    },
    {
      name: "Furkan",
      surname: "Eroğlu",
      email: "customer59@example.com",
      phone: "+905551115559",
    },
    {
      name: "Hatice",
      surname: "Yalçın",
      email: "customer60@example.com",
      phone: "+905551115560",
    },
    {
      name: "Ramazan",
      surname: "Soylu",
      email: "customer61@example.com",
      phone: "+905551115561",
    },
    {
      name: "Nisan",
      surname: "Sezer",
      email: "customer62@example.com",
      phone: "+905551115562",
    },
    {
      name: "Bora",
      surname: "Aksu",
      email: "customer63@example.com",
      phone: "+905551115563",
    },
    {
      name: "Ceyda",
      surname: "Uyar",
      email: "customer64@example.com",
      phone: "+905551115564",
    },
    {
      name: "Metin",
      surname: "Korkmaz",
      email: "customer65@example.com",
      phone: "+905551115565",
    },
    {
      name: "Burak",
      surname: "Erdoğan",
      email: "customer66@example.com",
      phone: "+905551115566",
    },
    {
      name: "Gizem",
      surname: "Bilgin",
      email: "customer67@example.com",
      phone: "+905551115567",
    },
    {
      name: "Kemal",
      surname: "Yıldırım",
      email: "customer68@example.com",
      phone: "+905551115568",
    },
    {
      name: "Özge",
      surname: "Çelik",
      email: "customer69@example.com",
      phone: "+905551115569",
    },
    {
      name: "Serkan",
      surname: "Gürsoy",
      email: "customer70@example.com",
      phone: "+905551115570",
    },
  ];

  for (const customerData of customers) {
    const customer = await prisma.user.upsert({
      where: { email: customerData.email },
      update: {},
      create: {
        ...customerData,
        hashedPassword: hashedCustomerPassword,
        role: Role.CUSTOMER,
        isVerified: true,
      },
    });
    console.log(`Müşteri kullanıcısı oluşturuldu: ${customer.email}`);
  }
  console.log(`${customers.length} adet müşteri kullanıcısı oluşturuldu.`);

  // 5. Oteller (10 adet)
  console.log("Oteller oluşturuluyor...");
  const hotels = [
    {
      name: "Grand Palace Hotel İstanbul",
      description:
        "İstanbul'un kalbinde, Boğaz manzaralı lüks otel. Tarihi yarımada üzerinde konumlanmış, modern konfor ve Osmanlı mimarisi bir arada.",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Sultanahmet, İstanbul",
      address: "Sultanahmet Meydanı No:15, Fatih/İstanbul",
      city: "İstanbul",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 15.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 0,
      taxId: "1234567890",
      taxOffice: "Fatih Vergi Dairesi",
      tradeRegistryNumber: "TR123456",
      businessLicense: "BL789012",
      addressProof: "https://example.com/address-proof.pdf",
      taxCertificate: "https://example.com/tax-certificate.pdf",
    },
    {
      name: "Blue Sea Resort Antalya",
      description: "Antalya'nın en güzel plajında, deniz manzaralı lüks resort",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Kemer, Antalya",
      address: "Kemer Sahil Caddesi No:25, Kemer/Antalya",
      city: "Antalya",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 10.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 1,
      taxId: "2345678901",
      taxOffice: "Kemer Vergi Dairesi",
      tradeRegistryNumber: "TR234567",
      businessLicense: "BL890123",
      addressProof: "https://example.com/address-proof-2.pdf",
      taxCertificate: "https://example.com/tax-certificate-2.pdf",
    },
    {
      name: "Mountain View Villa Bursa",
      description: "Uludağ'ın eteklerinde, dağ manzaralı özel villa",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Uludağ, Bursa",
      address: "Uludağ Yolu No:10, Nilüfer/Bursa",
      city: "Bursa",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.VILLA,
      ownerIndex: 2,
      taxId: "3456789012",
      taxOffice: "Nilüfer Vergi Dairesi",
      tradeRegistryNumber: "TR345678",
      businessLicense: "BL901234",
      addressProof: "https://example.com/address-proof-3.pdf",
      taxCertificate: "https://example.com/tax-certificate-3.pdf",
    },
    {
      name: "Forest Camp Çanakkale",
      description: "Kazdağları'nın kalbinde, doğayla iç içe kamp deneyimi",
      checkIn: "13:00",
      checkOut: "11:00",
      location: "Kazdağları, Çanakkale",
      address: "Kazdağları Milli Parkı, Bayramiç/Çanakkale",
      city: "Çanakkale",
      country: "Türkiye",
      rating: 4.3,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.CAMP,
      ownerIndex: 3,
      taxId: "4567890123",
      taxOffice: "Bayramiç Vergi Dairesi",
      tradeRegistryNumber: "TR456789",
      businessLicense: "BL012345",
      addressProof: "https://example.com/address-proof-4.pdf",
      taxCertificate: "https://example.com/tax-certificate-4.pdf",
    },
    {
      name: "Luxury Bungalow Fethiye",
      description: "Fethiye'nin en güzel koyunda, özel bungalov keyfi",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Fethiye, Muğla",
      address: "Ölüdeniz Mahallesi No:5, Fethiye/Muğla",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 20.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.BUNGALOW,
      ownerIndex: 4,
      taxId: "5678901234",
      taxOffice: "Fethiye Vergi Dairesi",
      tradeRegistryNumber: "TR567890",
      businessLicense: "BL123456",
      addressProof: "https://example.com/address-proof-5.pdf",
      taxCertificate: "https://example.com/tax-certificate-5.pdf",
    },
    {
      name: "Backpacker Hostel İstanbul",
      description: "Sultanahmet'in kalbinde, ekonomik ve sosyal konaklama",
      checkIn: "14:00",
      checkOut: "11:00",
      location: "Sultanahmet, İstanbul",
      address: "Sultanahmet Meydanı No:8, Fatih/İstanbul",
      city: "İstanbul",
      country: "Türkiye",
      rating: 4.1,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOSTEL,
      ownerIndex: 0,
      taxId: "6789012345",
      taxOffice: "Fatih Vergi Dairesi",
      tradeRegistryNumber: "TR678901",
      businessLicense: "BL234567",
      addressProof: "https://example.com/address-proof-6.pdf",
      taxCertificate: "https://example.com/tax-certificate-6.pdf",
    },
    {
      name: "Business Hotel İstanbul",
      description: "Levent'te, iş seyahatleri için ideal modern otel",
      checkIn: "15:00",
      checkOut: "12:00",
      location: "Levent, İstanbul",
      address: "Levent Mahallesi No:20, Beşiktaş/İstanbul",
      city: "İstanbul",
      country: "Türkiye",
      rating: 4.4,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 1,
      taxId: "7890123456",
      taxOffice: "Beşiktaş Vergi Dairesi",
      tradeRegistryNumber: "TR789012",
      businessLicense: "BL345678",
      addressProof: "https://example.com/address-proof-7.pdf",
      taxCertificate: "https://example.com/tax-certificate-7.pdf",
    },
    {
      name: "Seaside Resort Bodrum",
      description: "Bodrum'un en güzel plajında, deniz kenarında tatil",
      checkIn: "14:00",
      checkOut: "11:00",
      location: "Bodrum, Muğla",
      address: "Bodrum Sahil Caddesi No:30, Bodrum/Muğla",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 25.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 2,
      taxId: "8901234567",
      taxOffice: "Bodrum Vergi Dairesi",
      tradeRegistryNumber: "TR890123",
      businessLicense: "BL456789",
      addressProof: "https://example.com/address-proof-8.pdf",
      taxCertificate: "https://example.com/tax-certificate-8.pdf",
    },
    {
      name: "Historic Hotel Safranbolu",
      description:
        "Safranbolu'nun tarihi evlerinde, tarihi atmosferde konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Safranbolu, Karabük",
      address: "Tarihi Evler Mahallesi No:12, Safranbolu/Karabük",
      city: "Karabük",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 3,
      taxId: "9012345678",
      taxOffice: "Safranbolu Vergi Dairesi",
      tradeRegistryNumber: "TR901234",
      businessLicense: "BL567890",
      addressProof: "https://example.com/address-proof-9.pdf",
      taxCertificate: "https://example.com/tax-certificate-9.pdf",
    },
    {
      name: "Ski Resort Erzurum",
      description: "Palandöken'de, kayak tatili için mükemmel resort",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Palandöken, Erzurum",
      address: "Palandöken Kayak Merkezi No:5, Palandöken/Erzurum",
      city: "Erzurum",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 30.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 4,
      taxId: "0123456789",
      taxOffice: "Palandöken Vergi Dairesi",
      tradeRegistryNumber: "TR012345",
      businessLicense: "BL678901",
      addressProof: "https://example.com/address-proof-10.pdf",
      taxCertificate: "https://example.com/tax-certificate-10.pdf",
    },
    {
      name: "Kapadokya Cave Suites",
      description: "Kapadokya'nın eşsiz mağara odalarında lüks konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Göreme, Nevşehir",
      address: "Göreme Mevkii No:25, Nevşehir",
      city: "Nevşehir",
      country: "Türkiye",
      rating: 4.9,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 5,
      taxId: "1122334455",
      taxOffice: "Nevşehir Vergi Dairesi",
      tradeRegistryNumber: "TR112233",
      businessLicense: "BL112233",
      addressProof: "https://example.com/address-proof-11.pdf",
      taxCertificate: "https://example.com/tax-certificate-11.pdf",
    },
    {
      name: "Alanya Beach Resort",
      description: "Alanya'nın kristal sularında muhteşem bir tatil deneyimi",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Alanya, Antalya",
      address: "Kleopatra Plajı No:45, Alanya",
      city: "Antalya",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 20.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 6,
      taxId: "2233445566",
      taxOffice: "Alanya Vergi Dairesi",
      tradeRegistryNumber: "TR223344",
      businessLicense: "BL223344",
      addressProof: "https://example.com/address-proof-12.pdf",
      taxCertificate: "https://example.com/tax-certificate-12.pdf",
    },
    {
      name: "Marmaris Paradise Hotel",
      description: "Marmaris'in cennet koylarında huzurlu bir tatil",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Marmaris, Muğla",
      address: "İçmeler Mevkii No:67, Marmaris",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 15.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 7,
      taxId: "3344556677",
      taxOffice: "Marmaris Vergi Dairesi",
      tradeRegistryNumber: "TR334455",
      businessLicense: "BL334455",
      addressProof: "https://example.com/address-proof-13.pdf",
      taxCertificate: "https://example.com/tax-certificate-13.pdf",
    },
    {
      name: "Thermal Spa Resort Afyon",
      description: "Afyon'un şifalı sularında sağlık ve dinlenme",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Afyonkarahisar",
      address: "Termal Bölge No:89, Afyonkarahisar",
      city: "Afyonkarahisar",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.RESORT,
      ownerIndex: 8,
      taxId: "4455667788",
      taxOffice: "Afyon Vergi Dairesi",
      tradeRegistryNumber: "TR445566",
      businessLicense: "BL445566",
      addressProof: "https://example.com/address-proof-14.pdf",
      taxCertificate: "https://example.com/tax-certificate-14.pdf",
    },
    {
      name: "Ayder Highland Resort",
      description: "Karadeniz'in yemyeşil yaylalarında doğayla iç içe tatil",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Ayder Yaylası, Rize",
      address: "Ayder Yaylası No:12, Çamlıhemşin",
      city: "Rize",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.RESORT,
      ownerIndex: 9,
      taxId: "5566778899",
      taxOffice: "Rize Vergi Dairesi",
      tradeRegistryNumber: "TR556677",
      businessLicense: "BL556677",
      addressProof: "https://example.com/address-proof-15.pdf",
      taxCertificate: "https://example.com/tax-certificate-15.pdf",
    },
    {
      name: "Çeşme Marina Hotel",
      description: "Çeşme'nin berrak sularında yat limanı manzaralı konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Marina, Çeşme",
      address: "Marina Bölgesi No:34, Çeşme",
      city: "İzmir",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 10.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 10,
      taxId: "6677889900",
      taxOffice: "Çeşme Vergi Dairesi",
      tradeRegistryNumber: "TR667788",
      businessLicense: "BL667788",
      addressProof: "https://example.com/address-proof-16.pdf",
      taxCertificate: "https://example.com/tax-certificate-16.pdf",
    },
    {
      name: "Göcek Yacht Club Hotel",
      description: "Göcek'in masmavi koylarında yat limanı manzaralı konaklama",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Göcek, Muğla",
      address: "Göcek Marina No:56, Fethiye",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 11,
      taxId: "7788990011",
      taxOffice: "Fethiye Vergi Dairesi",
      tradeRegistryNumber: "TR778899",
      businessLicense: "BL778899",
      addressProof: "https://example.com/address-proof-17.pdf",
      taxCertificate: "https://example.com/tax-certificate-17.pdf",
    },
    {
      name: "Kalkan Infinity Villa",
      description: "Kalkan'ın eşsiz manzarasında sonsuzluk havuzlu lüks villa",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Kalkan, Antalya",
      address: "Kalamar Yolu No:78, Kaş",
      city: "Antalya",
      country: "Türkiye",
      rating: 4.9,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.VILLA,
      ownerIndex: 12,
      taxId: "8899001122",
      taxOffice: "Kaş Vergi Dairesi",
      tradeRegistryNumber: "TR889900",
      businessLicense: "BL889900",
      addressProof: "https://example.com/address-proof-18.pdf",
      taxCertificate: "https://example.com/tax-certificate-18.pdf",
    },
    {
      name: "Assos Stone House",
      description: "Assos'un tarihi dokusunda taş ev konseptli butik otel",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Assos, Çanakkale",
      address: "Behramkale Köyü No:23, Ayvacık",
      city: "Çanakkale",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 13,
      taxId: "9900112233",
      taxOffice: "Ayvacık Vergi Dairesi",
      tradeRegistryNumber: "TR990011",
      businessLicense: "BL990011",
      addressProof: "https://example.com/address-proof-19.pdf",
      taxCertificate: "https://example.com/tax-certificate-19.pdf",
    },
    {
      name: "Datça Peninsula Resort",
      description: "Datça'nın bakir koylarında doğayla iç içe tatil",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Datça, Muğla",
      address: "Datça Yarımadası No:45, Datça",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 15.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 14,
      taxId: "0011223344",
      taxOffice: "Datça Vergi Dairesi",
      tradeRegistryNumber: "TR001122",
      businessLicense: "BL001122",
      addressProof: "https://example.com/address-proof-20.pdf",
      taxCertificate: "https://example.com/tax-certificate-20.pdf",
    },
    {
      name: "Uzungöl Mountain Lodge",
      description: "Uzungöl'ün eşsiz manzarasında dağ evi konseptli konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Uzungöl, Trabzon",
      address: "Uzungöl Merkez No:67, Çaykara",
      city: "Trabzon",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 15,
      taxId: "1122334455",
      taxOffice: "Çaykara Vergi Dairesi",
      tradeRegistryNumber: "TR112233",
      businessLicense: "BL112233",
      addressProof: "https://example.com/address-proof-21.pdf",
      taxCertificate: "https://example.com/tax-certificate-21.pdf",
    },
    {
      name: "Side Ancient Hotel",
      description: "Side'nin antik kalıntıları arasında tarihi bir konaklama",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Side, Antalya",
      address: "Antik Kent No:89, Manavgat",
      city: "Antalya",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 20.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 16,
      taxId: "2233445566",
      taxOffice: "Manavgat Vergi Dairesi",
      tradeRegistryNumber: "TR223344",
      businessLicense: "BL223344",
      addressProof: "https://example.com/address-proof-22.pdf",
      taxCertificate: "https://example.com/tax-certificate-22.pdf",
    },
    {
      name: "Alaçatı Windsurf Resort",
      description: "Alaçatı'nın rüzgarlı sularında sörf ve tatil keyfi",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Alaçatı, İzmir",
      address: "Sörf Merkezi No:12, Çeşme",
      city: "İzmir",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.RESORT,
      ownerIndex: 17,
      taxId: "3344556677",
      taxOffice: "Çeşme Vergi Dairesi",
      tradeRegistryNumber: "TR334455",
      businessLicense: "BL334455",
      addressProof: "https://example.com/address-proof-23.pdf",
      taxCertificate: "https://example.com/tax-certificate-23.pdf",
    },
    {
      name: "Mardin Stone Mansion",
      description: "Mardin'in tarihi sokaklarında taş konakta konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Mardin",
      address: "Eski Mardin No:34, Artuklu",
      city: "Mardin",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 18,
      taxId: "4455667788",
      taxOffice: "Mardin Vergi Dairesi",
      tradeRegistryNumber: "TR445566",
      businessLicense: "BL445566",
      addressProof: "https://example.com/address-proof-24.pdf",
      taxCertificate: "https://example.com/tax-certificate-24.pdf",
    },
    {
      name: "Kartalkaya Winter Resort",
      description: "Kartalkaya'nın karlı zirvelerinde kayak ve kış tatili",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Kartalkaya, Bolu",
      address: "Kayak Merkezi No:56, Bolu",
      city: "Bolu",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 25.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 19,
      taxId: "5566778899",
      taxOffice: "Bolu Vergi Dairesi",
      tradeRegistryNumber: "TR556677",
      businessLicense: "BL556677",
      addressProof: "https://example.com/address-proof-25.pdf",
      taxCertificate: "https://example.com/tax-certificate-25.pdf",
    },
    {
      name: "Kuşadası Cruise Port Hotel",
      description: "Kuşadası limanında cruise gemileri manzaralı konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Kuşadası",
      address: "Liman Caddesi No:78, Kuşadası",
      city: "Aydın",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 15.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 20,
      taxId: "6677889900",
      taxOffice: "Kuşadası Vergi Dairesi",
      tradeRegistryNumber: "TR667788",
      businessLicense: "BL667788",
      addressProof: "https://example.com/address-proof-26.pdf",
      taxCertificate: "https://example.com/tax-certificate-26.pdf",
    },
    {
      name: "Sapanca Lake House",
      description: "Sapanca Gölü kıyısında lüks villa konseptli konaklama",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Sapanca, Sakarya",
      address: "Göl Kenarı No:90, Sapanca",
      city: "Sakarya",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.VILLA,
      ownerIndex: 21,
      taxId: "7788990011",
      taxOffice: "Sapanca Vergi Dairesi",
      tradeRegistryNumber: "TR778899",
      businessLicense: "BL778899",
      addressProof: "https://example.com/address-proof-27.pdf",
      taxCertificate: "https://example.com/tax-certificate-27.pdf",
    },
    {
      name: "Gaziantep Heritage Hotel",
      description: "Gaziantep'in tarihi atmosferinde butik konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Gaziantep",
      address: "Bakırcılar Çarşısı No:45, Şahinbey",
      city: "Gaziantep",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 22,
      taxId: "8899001122",
      taxOffice: "Gaziantep Vergi Dairesi",
      tradeRegistryNumber: "TR889900",
      businessLicense: "BL889900",
      addressProof: "https://example.com/address-proof-28.pdf",
      taxCertificate: "https://example.com/tax-certificate-28.pdf",
    },
    {
      name: "Ölüdeniz Beach Resort",
      description: "Ölüdeniz'in turkuaz sularında plaj ve tatil keyfi",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Ölüdeniz, Muğla",
      address: "Belcekız Plajı No:67, Fethiye",
      city: "Muğla",
      country: "Türkiye",
      rating: 4.9,
      discountRate: 20.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 23,
      taxId: "9900112233",
      taxOffice: "Fethiye Vergi Dairesi",
      tradeRegistryNumber: "TR990011",
      businessLicense: "BL990011",
      addressProof: "https://example.com/address-proof-29.pdf",
      taxCertificate: "https://example.com/tax-certificate-29.pdf",
    },
    {
      name: "Konya City Center Hotel",
      description: "Konya'nın merkezinde modern iş oteli",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Konya",
      address: "Mevlana Caddesi No:89, Selçuklu",
      city: "Konya",
      country: "Türkiye",
      rating: 4.4,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 24,
      taxId: "0011223344",
      taxOffice: "Konya Vergi Dairesi",
      tradeRegistryNumber: "TR001122",
      businessLicense: "BL001122",
      addressProof: "https://example.com/address-proof-30.pdf",
      taxCertificate: "https://example.com/tax-certificate-30.pdf",
    },
    {
      name: "Abant Nature Resort",
      description: "Abant Gölü'nün eşsiz doğasında huzurlu bir tatil",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Abant, Bolu",
      address: "Abant Gölü No:34, Bolu",
      city: "Bolu",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.RESORT,
      ownerIndex: 25,
      taxId: "1122334455",
      taxOffice: "Bolu Vergi Dairesi",
      tradeRegistryNumber: "TR112233",
      businessLicense: "BL112233",
      addressProof: "https://example.com/address-proof-31.pdf",
      taxCertificate: "https://example.com/tax-certificate-31.pdf",
    },
    {
      name: "Kars Winter Palace",
      description: "Kars'ın tarihi dokusunda kış tatili",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Kars",
      address: "Kaleiçi No:56, Kars",
      city: "Kars",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 20.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 26,
      taxId: "2233445566",
      taxOffice: "Kars Vergi Dairesi",
      tradeRegistryNumber: "TR223344",
      businessLicense: "BL223344",
      addressProof: "https://example.com/address-proof-32.pdf",
      taxCertificate: "https://example.com/tax-certificate-32.pdf",
    },
    {
      name: "Ayvalık Olive Resort",
      description: "Ayvalık'ın zeytin ağaçları arasında huzurlu tatil",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Ayvalık, Balıkesir",
      address: "Zeytinli Mahallesi No:78, Ayvalık",
      city: "Balıkesir",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.RESORT,
      ownerIndex: 27,
      taxId: "3344556677",
      taxOffice: "Ayvalık Vergi Dairesi",
      tradeRegistryNumber: "TR334455",
      businessLicense: "BL334455",
      addressProof: "https://example.com/address-proof-33.pdf",
      taxCertificate: "https://example.com/tax-certificate-33.pdf",
    },
    {
      name: "Rize Highland Lodge",
      description: "Rize'nin yemyeşil yaylalarında doğa ile iç içe",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Çamlıhemşin, Rize",
      address: "Ayder Yaylası No:90, Çamlıhemşin",
      city: "Rize",
      country: "Türkiye",
      rating: 4.7,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 28,
      taxId: "4455667788",
      taxOffice: "Rize Vergi Dairesi",
      tradeRegistryNumber: "TR445566",
      businessLicense: "BL445566",
      addressProof: "https://example.com/address-proof-34.pdf",
      taxCertificate: "https://example.com/tax-certificate-34.pdf",
    },
    {
      name: "Mersin Seaside Hotel",
      description: "Mersin'in masmavi denizinde tatil keyfi",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Mersin",
      address: "Sahil Bulvarı No:12, Mersin",
      city: "Mersin",
      country: "Türkiye",
      rating: 4.4,
      discountRate: 15.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 29,
      taxId: "5566778899",
      taxOffice: "Mersin Vergi Dairesi",
      tradeRegistryNumber: "TR556677",
      businessLicense: "BL556677",
      addressProof: "https://example.com/address-proof-35.pdf",
      taxCertificate: "https://example.com/tax-certificate-35.pdf",
    },
    {
      name: "Edirne Palace Hotel",
      description: "Edirne'nin tarihi dokusunda Osmanlı mimarisi",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Merkez, Edirne",
      address: "Selimiye Caddesi No:34, Edirne",
      city: "Edirne",
      country: "Türkiye",
      rating: 4.6,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 30,
      taxId: "6677889900",
      taxOffice: "Edirne Vergi Dairesi",
      tradeRegistryNumber: "TR667788",
      businessLicense: "BL667788",
      addressProof: "https://example.com/address-proof-36.pdf",
      taxCertificate: "https://example.com/tax-certificate-36.pdf",
    },
    {
      name: "Erzurum Mountain Resort",
      description: "Palandöken'in zirvesinde kayak keyfi",
      checkIn: "15:00",
      checkOut: "11:00",
      location: "Palandöken, Erzurum",
      address: "Kayak Merkezi No:56, Palandöken",
      city: "Erzurum",
      country: "Türkiye",
      rating: 4.8,
      discountRate: 25.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.RESORT,
      ownerIndex: 31,
      taxId: "7788990011",
      taxOffice: "Erzurum Vergi Dairesi",
      tradeRegistryNumber: "TR778899",
      businessLicense: "BL778899",
      addressProof: "https://example.com/address-proof-37.pdf",
      taxCertificate: "https://example.com/tax-certificate-37.pdf",
    },
    {
      name: "Adana Business Center",
      description: "Adana'nın merkezinde modern iş oteli",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Seyhan, Adana",
      address: "Atatürk Caddesi No:78, Seyhan",
      city: "Adana",
      country: "Türkiye",
      rating: 4.3,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 32,
      taxId: "8899001122",
      taxOffice: "Adana Vergi Dairesi",
      tradeRegistryNumber: "TR889900",
      businessLicense: "BL889900",
      addressProof: "https://example.com/address-proof-38.pdf",
      taxCertificate: "https://example.com/tax-certificate-38.pdf",
    },
    {
      name: "Samsun Black Sea Hotel",
      description: "Karadeniz'in incisi Samsun'da konforlu konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Atakum, Samsun",
      address: "Sahil Yolu No:90, Atakum",
      city: "Samsun",
      country: "Türkiye",
      rating: 4.5,
      discountRate: 10.0,
      isDiscounted: true,
      discountStartDate: new Date("2024-12-01T00:00:00Z"),
      discountEndDate: new Date("2024-12-31T23:59:59Z"),
      type: HotelType.HOTEL,
      ownerIndex: 33,
      taxId: "9900112233",
      taxOffice: "Samsun Vergi Dairesi",
      tradeRegistryNumber: "TR990011",
      businessLicense: "BL990011",
      addressProof: "https://example.com/address-proof-39.pdf",
      taxCertificate: "https://example.com/tax-certificate-39.pdf",
    },
    {
      name: "Diyarbakır Garden Hotel",
      description: "Diyarbakır surları yakınında huzurlu konaklama",
      checkIn: "14:00",
      checkOut: "12:00",
      location: "Sur, Diyarbakır",
      address: "Sur İçi No:12, Sur",
      city: "Diyarbakır",
      country: "Türkiye",
      rating: 4.4,
      discountRate: 0,
      isDiscounted: false,
      type: HotelType.HOTEL,
      ownerIndex: 34,
      taxId: "0011223344",
      taxOffice: "Diyarbakır Vergi Dairesi",
      tradeRegistryNumber: "TR001122",
      businessLicense: "BL001122",
      addressProof: "https://example.com/address-proof-40.pdf",
      taxCertificate: "https://example.com/tax-certificate-40.pdf",
    },
  ];

  // Otelleri oluştur
  for (const hotelData of hotels) {
    const ownerId = createdOwners[hotelData.ownerIndex]?.id;
    if (ownerId) {
      // Aynı isimde ve owner'a ait hotel var mı kontrol et
      const existingHotel = await prisma.hotel.findFirst({
        where: {
          name: hotelData.name,
          ownerId: ownerId,
          deletedAt: null,
        },
      });

      if (!existingHotel) {
        const hotel = await prisma.hotel.create({
          data: {
            name: hotelData.name,
            description: hotelData.description,
            checkIn: hotelData.checkIn,
            checkOut: hotelData.checkOut,
            location: hotelData.location,
            address: hotelData.address,
            city: hotelData.city,
            country: hotelData.country,
            rating: hotelData.rating,
            discountRate: hotelData.discountRate,
            isDiscounted: hotelData.isDiscounted,
            discountStartDate: hotelData.discountStartDate,
            discountEndDate: hotelData.discountEndDate,
            type: hotelData.type,
            ownerId: ownerId,
            taxId: hotelData.taxId,
            taxOffice: hotelData.taxOffice,
            tradeRegistryNumber: hotelData.tradeRegistryNumber,
            businessLicense: hotelData.businessLicense,
            addressProof: hotelData.addressProof,
            taxCertificate: hotelData.taxCertificate,
          },
        });
        console.log(`Otel oluşturuldu: ${hotel.name}`);

        // Grand Palace Hotel için özel odalar ekle
        if (hotel.name === "Grand Palace Hotel İstanbul") {
          const rooms = [
            {
              name: "Deluxe Boğaz Manzaralı Oda",
              description:
                "Boğaz manzaralı, 35 m² genişliğinde, king size yatak ve jakuzili banyo",
              price: 2500.0,
              maxAdults: 2,
              maxChildren: 1,
              floor: 5,
              roomNumber: 501,
              capacity: 3,
              bedCount: 1,
              type: RoomType.DELUXE,
              features: [
                RoomFeature.WIFI,
                RoomFeature.AIR_CONDITIONER,
                RoomFeature.TV,
                RoomFeature.MINIBAR,
                RoomFeature.BALCONY,
              ],
            },
            {
              name: "Standart Şehir Manzaralı Oda",
              description:
                "Şehir manzaralı, 25 m² genişliğinde, çift kişilik yatak",
              price: 1800.0,
              maxAdults: 2,
              maxChildren: 0,
              floor: 3,
              roomNumber: 302,
              capacity: 2,
              bedCount: 1,
              type: RoomType.STANDARD,
              features: [
                RoomFeature.WIFI,
                RoomFeature.AIR_CONDITIONER,
                RoomFeature.TV,
              ],
            },
            {
              name: "Presidential Suite",
              description:
                "Lüks suite oda, 65 m² genişliğinde, oturma odası ve jakuzili banyo",
              price: 4500.0,
              maxAdults: 3,
              maxChildren: 2,
              floor: 8,
              roomNumber: 801,
              capacity: 5,
              bedCount: 2,
              type: RoomType.PRESIDENTIAL,
              features: [
                RoomFeature.WIFI,
                RoomFeature.AIR_CONDITIONER,
                RoomFeature.TV,
                RoomFeature.MINIBAR,
                RoomFeature.BALCONY,
                RoomFeature.BATH_TUB,
                RoomFeature.SAFE_BOX,
              ],
            },
          ];

          for (const roomData of rooms) {
            const room = await prisma.room.create({
              data: {
                name: roomData.name,
                description: roomData.description,
                price: roomData.price,
                maxAdults: roomData.maxAdults,
                maxChildren: roomData.maxChildren,
                floor: roomData.floor,
                roomNumber: roomData.roomNumber,
                capacity: roomData.capacity,
                bedCount: roomData.bedCount,
                type: roomData.type,
                hotelId: hotel.id,
              },
            });

            // Oda özelliklerini ekle
            for (const feature of roomData.features) {
              await prisma.roomFeatureStatus.create({
                data: {
                  feature: feature,
                  isAvailable: true,
                  roomId: room.id,
                },
              });
            }

            console.log(`Oda oluşturuldu: ${room.name}`);
          }

          // Hotel özelliklerini ekle
          const hotelFeatures = [
            HotelFeatures.WIFI,
            HotelFeatures.POOL,
            HotelFeatures.SPA,
            HotelFeatures.PARKING,
            HotelFeatures.RESTAURANT,
            HotelFeatures.BREAKFAST_INCLUDED,
          ];

          for (const feature of hotelFeatures) {
            await prisma.hotelProps.create({
              data: {
                hotelId: hotel.id,
                feature: feature,
              },
            });
          }

          console.log(`Hotel özellikleri eklendi: ${hotel.name}`);
        }
      }
    }
  }

  console.log("Seed işlemi tamamlandı!");
  console.log("Oluşturulan kullanıcılar:");
  console.log(`- 1 Admin: admin@rotaly.com (Admin123!)`);
  console.log(`- 5 Owner: owner1@rotaly.com - owner5@rotaly.com (Owner123!)`);
  console.log(
    `- 5 Support: support1@rotaly.com - support5@rotaly.com (Support123!)`
  );
  console.log(
    `- 20 Customer: customer1@example.com - customer20@example.com (Customer123!)`
  );
  console.log("Oluşturulan oteller: 10 adet");
}

main()
  .catch((e) => {
    console.error("Seed işlemi sırasında hata oluştu:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
